dist: trusty
sudo: false
notifications:
  email: false
env:
- RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
  - stage: build and publish
    language: java
    jdk: oraclejdk8    
    before_install:
    - pwd
    - ls -la
    - chmod +x ./gradlew
    install: skip
    script: ./gradlew clean build
    before_deploy:
    - git config --local user.name "gayathrin"
    - git config --local user.email "gayathri.nelavigi@wipro.com"
    - git tag -f $RELEASE_TAG
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file: "build/libs/pal-tracker.jar"
      skip_cleanup: true
  - stage: deploy to review
    language: java
